openapi: 3.0.1
info:
  title: ApiMetadata
  version: 0.1.0
servers:
- url: "{server}:{port}/apiMetadata"
  variables:
    server:
      default: http://localhost
    port:
      default: "9090"
paths:
  /api:
    get:
      operationId: getApi
      parameters:
      - name: apiID
        in: query
        required: true
        schema:
          type: string
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiMetadataResponse'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
    put:
      operationId: putApi
      parameters:
      - name: apiID
        in: query
        required: true
        schema:
          type: string
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiMetadata'
        required: true
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
    post:
      summary: Create an API.
      operationId: postApi
      requestBody:
        description: api metadata
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ApiMetadata'
        required: true
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
    delete:
      operationId: deleteApi
      parameters:
      - name: apiID
        in: query
        required: true
        schema:
          type: string
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "202":
          description: Accepted
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /apiDefinition:
    get:
      operationId: getApidefinition
      parameters:
      - name: apiID
        in: query
        required: true
        schema:
          type: string
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: object
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /apiList:
    get:
      operationId: getApilist
      parameters:
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ApiMetadataResponse'
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /apiContent:
    put:
      operationId: putApicontent
      parameters:
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      - name: apiName
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "200":
          description: Ok
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
    post:
      operationId: postApicontent
      parameters:
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      - name: apiName
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              description: Any type of entity body
      responses:
        "201":
          description: Created
          content:
            text/plain:
              schema:
                type: string
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
  /apiFiles:
    get:
      operationId: getApifiles
      parameters:
      - name: orgName
        in: query
        required: true
        schema:
          type: string
      - name: apiID
        in: query
        required: true
        schema:
          type: string
      - name: fileName
        in: query
        required: true
        schema:
          type: string
      responses:
        default:
          description: Any Response
          content:
            '*/*':
              schema:
                description: Any type of entity body
        "500":
          description: InternalServerError
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        "400":
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
components:
  schemas:
    APIReview:
      required:
      - apiComment
      - apiID
      - apiName
      - apiRating
      - apiReviewer
      - reviewId
      type: object
      properties:
        reviewId:
          type: string
        apiComment:
          type: string
        apiRating:
          type: integer
          format: int64
        apiReviewer:
          type: string
        apiID:
          type: string
        apiName:
          type: string
      additionalProperties: false
    ApiArtifacts:
      required:
      - apiImages
      type: object
      properties:
        apiImages:
          type: object
          additionalProperties:
            type: string
    ApiArtifactsResponse:
      required:
      - apiContent
      - apiImages
      type: object
      properties:
        apiContent:
          type: array
          items:
            type: string
        apiImages:
          type: object
          additionalProperties:
            type: string
    ApiInfo:
      required:
      - additionalProperties
      - apiArtifacts
      - apiCategory
      - apiName
      - openApiDefinition
      - orgName
      - tags
      type: object
      properties:
        orgName:
          type: string
        apiName:
          type: string
        apiCategory:
          type: string
        tags:
          type: string
        openApiDefinition:
          type: object
        additionalProperties:
          type: object
          additionalProperties:
            type: string
        authorizedRoles:
          type: array
          items:
            type: string
        apiArtifacts:
          $ref: '#/components/schemas/ApiArtifacts'
    ApiInfoResponse:
      required:
      - additionalProperties
      - apiArtifacts
      - apiCategory
      - apiName
      - apiVersion
      - openApiDefinition
      - orgName
      - tags
      type: object
      properties:
        orgName:
          type: string
        apiName:
          type: string
        apiCategory:
          type: string
        tags:
          type: array
          items:
            type: string
        apiVersion:
          type: string
        authorizedRoles:
          type: array
          items:
            type: string
        openApiDefinition:
          type: object
        reviews:
          type: array
          items:
            $ref: '#/components/schemas/APIReview'
        additionalProperties:
          type: object
          additionalProperties:
            type: string
        apiArtifacts:
          $ref: '#/components/schemas/ApiArtifactsResponse'
    ApiMetadata:
      required:
      - apiInfo
      - serverUrl
      - throttlingPolicies
      type: object
      properties:
        apiInfo:
          $ref: '#/components/schemas/ApiInfo'
        throttlingPolicies:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ThrottlingPolicy'
        serverUrl:
          $ref: '#/components/schemas/ServerUrl'
      description: Description.
    ApiMetadataResponse:
      required:
      - apiInfo
      - serverUrl
      - throttlingPolicies
      type: object
      properties:
        apiInfo:
          $ref: '#/components/schemas/ApiInfoResponse'
        throttlingPolicies:
          type: array
          nullable: true
          items:
            $ref: '#/components/schemas/ThrottlingPolicy'
        serverUrl:
          $ref: '#/components/schemas/ServerUrl'
    ErrorPayload:
      required:
      - message
      - method
      - path
      - reason
      - status
      - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
    ServerUrl:
      required:
      - productionUrl
      - sandboxUrl
      type: object
      properties:
        sandboxUrl:
          type: string
        productionUrl:
          type: string
      description: Description.
    ThrottlingPolicy:
      required:
      - description
      - policyName
      - type
      type: object
      properties:
        type:
          type: string
        policyName:
          type: string
        description:
          type: string
      description: Description.
