[package]
org = "divya"
name = "devportal"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[persist]
datastore = "inmemory"
module = "devportal.store"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.2.0"

