[package]
org = "divya"
name = "devportal"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true



[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.inmemory-native"
version = "1.2.0"

[persist]
datastore = "mysql"
module = "devportal"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "persist.sql-native"
version = "1.2.0"

