[devportal]
host = "localhost"
port = 3306
user = "root"
password = "Sachiesh.13"
database = "DevPortal"

[devportal.store]
host = "localhost"
port = 3306
user = "root"
password = "Sachiesh.13"
database = "DevPortal"

