[devportal]
host = "localhost"
port = 3306
user = "root"
password = "root"
database = "devportal"

[devportal.store]
host = "localhost"
port = 3306
user = "root"
password = "root"
database = "devportal"

